apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-jenkins
#GCE-Presistant-Disk
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
#Means GCP will wait for the first pod to ask for the volume and will create it in the same zone of the pod
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc 
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "storage-jenkins" 
  resources:
    requests:
      storage: 30Gi 